[build]
target = "index.html"
dist = "dist"

[serve]
port = 9000

[[proxy]]
backend = "http://127.0.0.1:9001/api/"

<<<<<<< Updated upstream
[[proxy]]
backend = "http://127.0.0.1:9001/auth/"
=======
>>>>>>> Stashed changes
