name: Build CooperCo

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test app
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Trunk
        uses: taiki-e/install-action@trunk

      - name: Run cargo checks
        run: cargo check

      - name: Run cargo tests
        run: cargo test

      - name: Build frontend
        run: trunk build --release --config frontend/Trunk.toml

      - name: Build backend
        run: cargo build --release -p backend
